export const IMAGES_LOAD_START = 'IMAGES_LOAD_START';
export const IMAGES_LOAD_SUCCESS = 'IMAGES_LOAD_SUCCESS';
export const IMAGES_LOAD_ERROR = 'IMAGES_LOAD_ERROR';

export const INPUT_CHANGE_SUCCESS = 'INPUT_CHANGE_SUCCESS';
export const INPUT_CHANGE_ERROR = 'INPUT_CHANGE_ERROR';